# Generated by Django 4.2.21 on 2025-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lector_password_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='lectors', to='core.student'),
        ),
    ]
