# Generated by Django 4.2.21 on 2025-05-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lector_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.lector')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='core.student')),
            ],
        ),
    ]
