# Generated by Django 4.2.11 on 2025-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_type',
            field=models.CharField(blank=True, choices=[('homework', 'Homework'), ('participation', 'Participation'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('project', 'Project')], max_length=20, null=True),
        ),
    ]
