# Generated by Django 4.2.21 on 2025-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
