# Generated by Django 4.2.21 on 2025-05-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lector_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='sender_object_id',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='receiver_content_type',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='receiver_object_id',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='sender_object_id',
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='core.student'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_private_messages', to='core.student'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_private_messages', to='core.student'),
        ),
    ]
