# Generated by Django 4.2.21 on 2025-05-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_remove_groupchatmessage_sender_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='sender',
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='sender_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='sender_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='receiver_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='receiver_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='sender_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='sender_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
