# Generated by Django 4.2.21 on 2025-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_groupchatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
