# Generated by Django 4.2.21 on 2025-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_groupchatmessage_file_groupchatmessage_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
