# Generated by Django 4.2.21 on 2025-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_privatechat_file_url_privatechat_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
