# Generated by Django 4.2.21 on 2025-06-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lector_is_online_student_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_online',
        ),
    ]
